version: '3.8'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - app-network

  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:

